#!/bin/tcsh

# This is a simple script which will carry out all of the basic steps
# required to make a DISOPRED prediction. Note that it assumes that the
# following programs are in the appropriate directories:
# blastpgp - PSIBLAST executable (from NCBI toolkit)
# makemat - IMPALA utility (from NCBI toolkit)
# psipred - PSIPRED V2 program
# psipass2 - PSIPRED V2 program
# disopred - DISOPRED program
#
# NOTE: This is very similar to the runpsipred script included in the PSIPRED
# package.
#

# The name of the BLAST data bank
set dbname = allfilt

# Where the NCBI programs have been installed
set ncbidir = /usr/local/bin

# Where the PSIPRED V2 and DISOPRED programs have been installed
set execdir = /usr/local/bin

# Where the PSIPRED V2 and DISOPRED data files have been installed
set datadir = /usr/local/lib/psipred

set basename = $1:r
set rootname = $basename:t
set outname = $basename.chk

\cp -f $1 psitmp.fasta

echo "Running PSI-BLAST with sequence" $1 "..."

$ncbidir/blastpgp -b 0 -j 3 -h 0.001 -d $dbname -i psitmp.fasta -C psitmp.chk >& $rootname.blast

echo "Predicting secondary structure..."

echo psitmp.chk > psitmp.pn
echo psitmp.fasta > psitmp.sn
$ncbidir/makemat -P psitmp

echo PSIPRED Pass1 ...

$execdir/psipred psitmp.mtx $datadir/weights.dat $datadir/weights.dat2 $datadir/weights.dat3 $datadir/weights.dat4 > $rootname.ss

echo PSIPRED Pass2 ...

$execdir/psipass2 $datadir/weights_p2.dat 1 0.98 1.09 $rootname.ss2 $rootname.ss > $rootname.horiz

echo Predicting disordered regions ...

$execdir/disopred $datadir/disoweights.dat psitmp.mtx $rootname.ss2 > $rootname.diso

# Remove temporary files

echo Cleaning up ...
\rm -f psitmp.* error.log

echo "Final output files:" $rootname.ss2 $rootname.horiz $rootname.diso
echo "Finished."
