#!/bin/tcsh

# This is a simple script which will carry out all of the basic steps
# required to make a DISOPRED prediction. Note that it assumes that the
# following programs are in the appropriate directories:
# blastpgp - PSIBLAST executable (from NCBI toolkit)
# makemat - IMPALA utility (from NCBI toolkit)
# psipred - PSIPRED V2 program
# psipass2 - PSIPRED V2 program
# disopred - DISOPRED program
#
# NOTE: This is very similar to the runpsipred script included in the PSIPRED
# package.
#
set path = $2
# The name of the BLAST data bank
#set dbname = allfilt
set dbname = /data/blast/big
# Where the NCBI programs have been installed
set ncbidir = /usr/pub/molbio/blast
#set rundir = /nfs/home5/schles/md/psipred
set rundir = .
# Where the PSIPRED V2 programs have been installed
#set execdir = /nfs/home5/schles/md/psipred/bin
set execdir = $path/psipred/bin
# Where the PSIPRED V2 data files have been installed
set datadir = $path/psipred/data
set basename = $1:r
set rootname = $basename:t
set outname = $basename.chk

\cp -f $1 $rundir/psitmp$rootname.fasta
#$path/psitmp$rootname.fasta
echo "Running PSI-BLAST with sequence" $1 "..."
echo "fasta=$path/psitmp$rootname.fasta datadir=$datadir basename=$basename rootname=$rootname outname=$outname execdir=$execdir 1=$1 2=$2"

echo "$ncbidir/blastpgp -b 0 -j 3 -h 0.001 -d $dbname -i $rundir/psitmp$rootname.fasta -C $rundir/psitmp$rootname.chk >& $path/$rootname.blast"
$ncbidir/blastpgp -b 0 -j 3 -h 0.001 -d $dbname -i $rundir/psitmp$rootname.fasta -C $rundir/psitmp$rootname.chk >& $path/$rootname.blast

echo "Predicting secondary structure..."

echo psitmp$rootname.chk > psitmp$rootname.pn
echo psitmp$rootname.fasta > psitmp$rootname.sn
$ncbidir/makemat -P $rundir/psitmp$rootname

echo PSIPRED Pass1 ...

$execdir/psipred $path/psitmp$rootname.mtx $datadir/weights.dat $datadir/weights.dat2 $datadir/weights.dat3 $datadir/weights.dat4 > $path/$rootname.ss

echo PSIPRED Pass2  ...

#$execdir/psipass2 $datadir/weights_p2.dat 1 1.0 1.3 $rootname.ss2 $rootname.ss > $rootname.horiz

$execdir/psipass2 $datadir/weights_p2.dat 1 0.98 1.09 $path/$rootname.ss2 $path/$rootname.ss > $path/$rootname.horiz

echo Predicting disordered regions ...

echo "$execdir/disopred $datadir/disoweights.dat $path/psitmp$rootname.mtx $path/$rootname.ss2 > $path/$rootname.diso"
#$execdir/disopred $datadir/disoweights.dat psitmp$rootname.mtx $rootname.ss2 > $rootname.diso
$execdir/disopred $path/psipred/disoweights.dat $path/psitmp$rootname.mtx $path/$rootname.ss2 >$path/$rootname.diso
# Remove temporary files

echo Cleaning up ...
#\rm -f psitmp$rootname.* error.log

echo "Final output files:" $rootname.ss2 $rootname.horiz $rootname.diso
echo "Finished."
